= README

== Goals

Little Ansible role to install a monitoring stack with Prometheus, Grafana, Node-Exporter, Telegraf and InfluxDB.

== What remains to be done ?

- use handlers
- create ansible tags
- create a verify test/molecule
- add your value!

== Vars

Some variables are used in the file `main.yml`.

== Grafana

Stock configuration, no options or tweaks used. Listen on 0.0.0.0:3000. Default user is `admin` with password `admin`.

== Prometheus

- listen on 0.0.0.0:9090
- service forced to store data for 180 days (see systemd unit file in tasks/templates/prometheus.service.j2) - variable `--storage.tsdb.retention.time`

== How to use it ?

=== Test it with molecule

Simple ! Use the venv.sh script to enter to the matrix (c).

```bash
source venv.sh
```

This virtualenv will bring you needed tools. You will in the virtualenv automatically. You are now ready to create virtual machines.

```bash
molecule create
```

And then use the playbook

```bash
molecule converge
```

When you're all set, destroy it.

```bash
molecule destroy
```

=== Use this role in another ansible playbook

Incorpore this role on your playbook and go ! Add this block on your `requirements.yml`

```bash
---
roles:
  - src: git@github.com:Mettmett/ansible-monitoring.git
    scm: git
```
