= README

== Goals

Little Ansible role to install a monitoring stack with Prometheus, Grafana, Node-Exporter, Loki (with promtail), Telegraf and InfluxDB.

== Vars

Some variables are used in the file `play.yml`. They're here to be used with molecule easily. You can surcharge them in your playbook.

== Blackbox_Exporter

Stock configuration, no options or tweaks used.

== Grafana

Stock configuration, no options or tweaks used. Listen on 0.0.0.0:3000. Default user is `admin` with password `admin`.

- auto-provisionning of datasources (prometheus and loki, installed locally)

== Prometheus

- listen on 0.0.0.0:9090
- service forced to store data for 180 days (see systemd unit file in tasks/templates/prometheus.service.j2) - variable `--storage.tsdb.retention.time`

== Node_Exporter

Have some metrics easily of your host with this package. No tweaks, simple use.

== Loki and Promtail

Used to view logs into Grafana. Default configuration used.

== Nginx_Exporter

Stock configuration, no options or tweaks used. Scrape by default `http://localhost:81/stub_status` (can be changed with the vars `nginx_uri_status`)

== MysqlD_Exporter

Stock configuration, no options or tweaks used. Variables are used to specify the user able to connect to your SQL server and operate on it (SELECT on performance_schema)

== How to use it ?

=== Test it with molecule

Simple ! Use the venv.sh script to enter to the matrix (c).

[source,bash]
----
source venv.sh
----

This virtualenv will bring you needed tools. You will in the virtualenv automatically. You are now ready to create virtual machines and then use the playbook. 

[source,bash]
----
molecule create && molecule converge
----

When you're all set, destroy it.

[source,bash]
----
molecule destroy
----

=== Use this role in another ansible playbook

Incorpore this role on your playbook and go ! Add this block on your `requirements.yml`

[source,bash]
----
roles:
  - src: git@github.com:Mettmett/ansible-monitoring.git
    scm: git
----
