---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint: |
  set -e .
  yamllint .
  ansible-lint

platforms:
  - name: monitoring-ubuntu
    box: ubuntu/focal64
  - name: monitoring-debian
    box: debian/buster64
  - name: monitoring-debian11
    box: debian/bullseye64

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../play.yml

scenario:
  name: default

verifier:
  name: ansible
