---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint: |
  set -e .
  yamllint .
  ansible-lint

platforms:
  - name: monitoring-ubuntu
    box: ubuntu/focal64
    interfaces:
      - auto_config: true
        ip: 192.168.56.9
        netmask: 24
        network_name: private_network
  - name: monitoring-debian
    box: debian/buster64
    interfaces:
      - auto_config: true
        ip: 192.168.56.10
        netmask: 24
        network_name: private_network
  - name: monitoring-debian11
    box: debian/bullseye64
    interfaces:
      - auto_config: true
        ip: 192.168.56.11
        netmask: 24
        network_name: private_network

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: ansible
