---

- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: (sys) update host apt cache
      apt:
        cache_valid_time: 3600
        update_cache: true

    - name: (sys) install sys tools
      apt:
        name: "{{ item }}"
        state: present
        install_recommends: false
      loop:
        - curl
        - git
        - rsync
        - tar
        - unzip
        - wget

    - name: python3-minimal for ansible
      shell: "test -e /usr/bin/python3 || (apt update -y && apt install python3-minimal --no-install-recommends)"
      changed_when: false
