---

- name: Verify
  hosts: all
  become: true
  tasks:
  - name: (check) Test if services are started and enabled
    systemd:
      enabled: true
      name: "{{ item }}"
      state: started
    loop:
      - blackbox_exporter.service
      - grafana-server.service
      - loki.service
      - node_exporter.service
      - prometheus.service
      - promtail.service

  - name: (check) Test if services ports are open and reachable
    wait_for:
      port: "{{ item }}"
    loop:
      - 3000
      - 9080
      - 9090
      - 9100
      - 9115

  - name: (check) Test if Prometheus web interface is OK
    uri:
      status_code: 200
      url: "http://localhost:9090/status"

  - name: (check) Test if Grafana web interface is OK
    uri:
      status_code: 200
      url: "http://localhost:3000"

  - name: (check) Test if node_exporter metrics is OK
    uri:
      status_code: 200
      url: "http://localhost:9100/metrics"

  - name: (check) Test if blackbox_exporter metrics is OK
    uri:
      status_code: 200
      url: "http://localhost:9115/metrics"

  - name: (check) Test if promtail web interface is OK
    uri:
      status_code: 200
      url: "http://localhost:9080/targets"
